# Generated by Django 4.0.3 on 2022-03-28 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MoneyAcc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('private_key', models.CharField(blank=True, max_length=100, null=True)),
                ('public_key', models.CharField(blank=True, max_length=100, null=True)),
                ('blance', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
    ]
